# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi=vim
alias gst='git status'
alias glog='git log --oneline --decorate --graph'
alias ..='cd ..'

export EDITOR=vim
export PS1='\[\e[1;32m\]\u@\h\[\e[0;33m\] \w \[\e[1;34m\]\$\[\e[0m\] '
#export PS1='\[\e]0;\h:\w\a\]\n\[\e[1;32m\]\u@\h\[\e[0;33m\] \w \[\e[0m[\D{%H:%M:%S}]\n\[\e[1;$((31+3*!$?))m\]\$\[\e[0m\] '

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
